### ISSUE TITLE
file=php://input

### ISSUE THREAD

**Issue by Homyee** [Hack-Free/HackBar#1]
I can't post data
for example:
```
index.php
<?php
$file  = $_GET['file'];
include($file);
?>
```

www.xxx.com/index.php?file=php://input
[POST]    `<?php phpinfo() ?>`

**Comment by Chewbaka69** [comment]
Why you can't? have you check the box to add post data?

**Comment by Homyee** [comment]
Yes, I put `<?php phpinfo(); ?>` in the post box, and I click execute, but nothing happened. when I add a '='  in the box ,`=<?php phpinfo(); ?>` , it works. Actually, I must put a '=' in it, otherwise, it doesn't respond. I 'm sure I used it corrently, because I test the code in another hackbar---New hackebar  , a Firefox extension.  I can got the phpinfo page. 
I use Firefox extension, firefox is the latest Chinese version. I don't know if there is a problem with the software version. Both my mac and win have the problem.

**Comment by Chewbaka69** [comment]
Ok i wil check on my server, i will reproduce the test.

**Comment by Chewbaka69** [comment]
I have try with, New Hackbar, with Max HackBar and nothing works, so i think it's because it can not be possible.

To use php://input, i think you need to use this:
`file_get_contents("php://input");`
https://www.php.net/manual/en/wrappers.php.php#wrappers.php.input

**Comment by w616780** [comment]
Hello @Chewbaka69 ，
I met the same problem with above too. When I use `php://input`, I want to add `file = php://intput` into GET param and add `<?php phpinfo(); ?>`  **without `xx=xx`** into POST param . As you know,  raw data directly added into post data is not allowed that is mentioned in https://github.com/Hack-Free/HackBar/issues/2#issuecomment-526500568. I want to know how to send POST DATA withou `xx=xx` when I attend to use `php://input`?

Thank you! Good Wishes!
