### ISSUE TITLE
[BUG] "The extension "HackBar V2" is not allowed to access about:newtab manifest.json" appears

### ISSUE THREAD

**Issue by MemoryShadow** [Hack-Free/HackBar#10]
When I click the execute button, nothing happens and I am prompted with this message in the console

![图片](https://user-images.githubusercontent.com/31596045/183286605-3f58059c-db72-410e-a382-20c4f6491211.png)

---

OS: Manjaro/Linux 5.15.57-2 (x64)
Browser: firefox developer edition 104.0b2 (x64)

**Comment by Chewbaka69** [comment]
Hello,

This is not a bug, you are on "about:newtab".
You need to put an url and open the hack bar to manipulate the data.

**Comment by MemoryShadow** [comment]
Indeed, thank you very much for your reply, I'm sorry for wasting your time
