### ISSUE TITLE
貌似只能post键值对,没办法post任意值或者json

### ISSUE THREAD

**Issue by BingQianceng** [Hack-Free/HackBar#11]

**Comment by Chewbaka69** [comment]
Can you please write in English!

**Comment by BingQianceng** [comment]
it is can not post json,

**Comment by Chewbaka69** [comment]
Ok thanks.
I will try to reproduce.
Because I have already test and it work.
But it is only possible when the request is by default a POST.

**Comment by hazzel-cn** [comment]
@BingQianceng did you add the proper Content-Type header in your request?

试一下在Header里面加上 Content-Type: application/json?

**Comment by Chewbaka69** [comment]
Not reproduce sorry
