### ISSUE TITLE
When performing md5 on Chinese, there may be calculation errors

### ISSUE THREAD

**Issue by LTLTLXEY** [Hack-Free/HackBar#15]
When performing md5 on Chinese, there may be calculation errors

such as "中文"

on HackBar-V2, the md5 result is "eeff7ad1ae620adc859df95b565cd590"
![图片](https://github.com/user-attachments/assets/6a609f4c-44af-4b52-a4eb-97a056091928)
![图片](https://github.com/user-attachments/assets/fd042a25-1866-43ab-b545-1b0fa0a616f6)

But this is not right，as you see, Calculate the md5 value of "中文" on other platforms or directly using Windows system commands

![图片](https://github.com/user-attachments/assets/36b33ab2-02e6-4c40-896d-644f6f1ce2a1)
![图片](https://github.com/user-attachments/assets/d45ab6b2-267c-4d50-ab6f-911126315bb4)

I hope the author can fix this bug, thank you~

**Comment by Chewbaka69** [comment]
Oh yes thanks!

I will fix it asap, with the right algo ;)

**Comment by Chewbaka69** [comment]
I have pushed the new version with the fix ;)
