### ISSUE TITLE
"Post Data" cannot work on your HackBar V2 2.3.0 on firefox 60.8 esr

### ISSUE THREAD

**Issue by simoncaogit** [Hack-Free/HackBar#2]
When I chose "Post data" and click button "Execute" , It cannot work.  as a comparision, When I do the same operation on Old Hackbar 2.1.3 , it works. 

Please solve it , thanks for your great work.

Simon

**Comment by Chewbaka69** [comment]
Ok i will check this today.

**Comment by Chewbaka69** [comment]
Can you give me an example of the Post data you want to send?

**Comment by Chewbaka69** [comment]
Actually raw data cannot be send :/
You only send data like this:
`test=data`
