### ISSUE TITLE
firefox addon hackber  can not execute when load the url

### ISSUE THREAD

**Issue by mtcz91** [Hack-Free/HackBar#5]
firefox addon hackber  can not execute when load the url

**Comment by Chewbaka69** [comment]
Hello, please give me some information:

Exemple of URL you load :
Firefox version :
HackBar version :
OS :
Error in Firefox console:

**Comment by mtcz91** [comment]
Firefox version :  77.0.1 (64 位)
HackBar version : 2.5.2
OS : win10 professional edition 2004 （OS inner edition 19041.329）# I just update win10 to 2004 by  Windows10upgrade a week ago
Error in Firefox console: none
I have send  a test gif demo to your email box.

**Comment by mtcz91** [comment]
Firefox version :  77.0.1 (64 位)

HackBar version : 2.5.2

OS : win10 professional edition 2004 （OS inner edition 19041.329）# I just update win10 to 2004 by  Windows10upgrade a week ago

Error in Firefox console: none

a test gif demo  in mail attachment
















At 2020-06-16 17:26:20, "Chewbaka" <notifications@github.com> wrote:

Hello, please give me some information:

Exemple of URL you load :
Firefox version :
HackBar version :
OS :
Error in Firefox console:

**Comment by mtcz91** [comment]
Firefox version : 77.0.1 (64 位)
HackBar version : 2.5.2
OS : win10 professional edition 2004 （OS inner edition 19041.329）# I just update win10 to 2004 by Windows10upgrade a week ago
Error in Firefox console: none
I have send a test gif demo to your email box.

**Comment by Chewbaka69** [comment]
I haven't received your test gif demo.
