### ISSUE TITLE
host错乱

### ISSUE THREAD

**Issue by cns1rius** [Hack-Free/HackBar#9]
在使用过后，新建标签页打开网页失败，经查看，为header host错乱导致，需手动将新页面host删除才可正常访问

**Comment by Chewbaka69** [comment]
Translation:
> After using it, the new tab page failed to open the webpage. After viewing, it was caused by the header host disorder. You need to manually delete the new page host to access it normally.

Ok i will investigate on it, thanks.
But speak english ;)

**Comment by Chewbaka69** [comment]
I reproduce the bug, i will work on it asap ;)
